### ISSUE TITLE
Lashtail Raptor Disarm

### ISSUE THREAD

**Issue by SnowyNoS** [NostraliaWoW/mangoszero#118]
http://db.vanillagaming.org/?npc=686#abilities

Their disarm debuff actually applies as a buff and you can just cancel it lol

Forum post,
http://nostralia.org/forums/viewtopic.php?f=23&t=122

**Comment by sundayz** [comment]
Related to: #6 

Both spells need CANT_CANCEL or PASSIVE SpellAttributes.
