### ISSUE TITLE
intimidating shout

### ISSUE THREAD

**Issue by SnowyNoS** [NostraliaWoW/mangoszero#119]
Primary target after the fear ends runs back to where he was standing before combat and will stand there, still in combat with you. I've done this several times and stood at range to bandage and shoot them, and they dont run back. Me moving into their range they will resume attacking, but walking away again they won't chase.

Useful bug right now if you're dying in combat, but doesn't seem intentional.

Forum post,
http://nostralia.org/forums/viewtopic.php?f=14&t=109

**Comment by sundayz** [comment]
As far as I know, main target is supposed to be feared but stay still, while others around you run in fear like normal.

**Comment by sundayz** [comment]
See a49cc03.

**Comment by sundayz** [comment]
Fixed, re-open if this causes issues with other stuns and fears.
