### ISSUE TITLE
Mind Flay

### ISSUE THREAD

**Issue by SnowyNoS** [NostraliaWoW/mangoszero#130]
When casting Mind Flay the moment it gets in range it will cast but not do anything but it will still cost mana. This is with Shadow reach talent, not sure how it is without. The bug happens consistently in the same range.

post,
http://nostralia.org/forums/viewtopic.php?f=19&t=101

**Comment by pjfry651** [comment]
Related to #13

**Comment by pjfry651** [comment]
Have a fix for this but waiting on outcome of discussion with @natrist about correct spell "leeway" values that we should fix at the same time.
