### ISSUE TITLE
 Shaman Searing Totem attacks neutral targets.

### ISSUE THREAD

**Issue by SnowyNoS** [NostraliaWoW/mangoszero#138]
Like title, shaman searing totem will attack neutral mobs, had it happen against yellow zhevras and plainstriders in the barrens.
edit. Attacks critters also.

post
http://nostralia.org/forums/viewtopic.php?f=25&t=26

**Comment by sundayz** [comment]
This is the related check inside of TotemAI.cpp:

```c++
    if (!victim ||
        !victim->IsTargetableForAttack() || !m_creature->IsWithinDistInMap(victim, max_range) ||
        m_creature->IsFriendlyTo(victim) || !victim->IsVisibleForOrDetect(m_creature, m_creature, false) ||
        victim->IsNeutralToAll())
```

**Comment by sundayz** [comment]
Pretty sure this will require implementing something similar to Trinity's IsValidAttackTarget()

See Unit.cpp:

https://github.com/TrinityCore/TrinityCore/blob/3.3.5/src/server/game/Entities/Unit/Unit.cpp#L8624

There are multiple "neutral" factions so faction mask checking needs to be done, I think.

**Comment by pjfry651** [comment]
I've used Unit.cpp's IsHostileTo function and slightly updated the way Totems process their targets. This solves the issue of totems attacking neutral mobs and critters (until you aggro them, then it will attack them as they turn hostile).

I assume totems should only attack units that are hostile, are there any exceptions to this?
