### ISSUE TITLE
Investigate the Alchemist Shop

### ISSUE THREAD

**Issue by SnowyNoS** [NostraliaWoW/mangoszero#139]
The Mage quest at level 15-16 in Undercity (sorry I have logged off and forget the name of the quest) - it involved collecting a scroll and a box of containers and heading over to the alchemy shop where andon grant is and using the scroll of manifestation near void rifts. Hopefully that describes it.

The rifts don't appear and nothing spawns. You can keep using the manifestation thing but nothing happens. Thx!

Quest in question
http://db.vanillagaming.org/?quest=1960

Post,
http://nostralia.org/forums/viewtopic.php?f=28&t=104

**Comment by sundayz** [comment]
Fixed in 7ea4da5.
