### ISSUE TITLE
Class Bug - Warrior

### ISSUE THREAD

**Issue by Gutr0t** [NostraliaWoW/mangoszero#14]
Block doesn't appear to calculate correctly. With a 38 block shield and 249 strength, can block 561 damage. Formula should be X = Block Value + Strength/2. At 38 block and 249 strength should equal 162.5 damage blocked. 

Example; http://puu.sh/trnBc/b126dc965a.jpg

**Comment by pjfry651** [comment]
Hey Gut do we have a source for that block formula?
