### ISSUE TITLE
Bloodfury Roguefeather Trash being Spammed

### ISSUE THREAD

**Issue by Gutr0t** [NostraliaWoW/mangoszero#140]
[Bloodfury Roguefeather](http://db.vanillagaming.org/?npc=4023) are casting the ability [thrash](http://db.vanillagaming.org/?spell=3391) too frequently resulting in up to 4 hits consecutively without a consequential cooldown. When they use thrash they could hit twice in a row but sometimes they hit 4 times.

**Comment by sundayz** [comment]
Possible issue where Thrash can proc off itself?

Thrash is an aura granting a chance to cause 2 extra attacks. The NPC doesn't spam the ability.

**Comment by pjfry651** [comment]
Confirmed that almost all spells with the SPELL_EFFECT_ADD_EXTRA_ATTACKS effect can proc again from the extra attacks. Theoretically this could one-shot players if it proc'd enough times!
