### ISSUE TITLE
Drowning

### ISSUE THREAD

**Issue by SnowyNoS** [NostraliaWoW/mangoszero#141]
Summary - Drowning is causing instant death, as soon as you run out of air. In my combat log there is 5-6 ticks of damage, but they are all happening instantly when breath runs out. 
Location - Underwater. 
Steps to Reproduce - Play anything other than undead and go swimming =)

Post,
http://nostralia.org/forums/viewtopic.php?f=28&t=140

**Comment by SnowyNoS** [comment]
Maybe need to make

**Comment by sundayz** [comment]
Still an issue?

**Comment by Gutr0t** [comment]
I tried this on live server couldn't replicate the issue so Snowy closed this. I don't believe it's an issue, it sounds like the player experiences lag and the damage caught up to him.

**Comment by SnowyNoS** [comment]
As per @Gutr0t  we both did a quick test and we think its working fine.
