### ISSUE TITLE
Improved Aspect of the Hawk

### ISSUE THREAD

**Issue by SnowyNoS** [NostraliaWoW/mangoszero#146]
Name - Spell Improved Aspect of the Hawk ID 19552
Summary - Procs off melee attacks
Location - N/A
Steps to Reproduce - Attack in melee with the talents chosen
Screen Shots/Video - N/A
Extra Information - Reported by Pisani (in game name)

post,
http://nostralia.org/forums/viewtopic.php?f=29&t=146

**Comment by pjfry651** [comment]
This proc only has the PROC_FLAG_SUCCESSFUL_RANGED_SPELL_HIT flag, meaning it should never proc from anything other than a successful ranged hit. I cannot reproduce. Please reopen if you can provide more specifics (spell ranks, specific mobs, etc.) or even a video.
