### ISSUE TITLE
Scarlet Monastery

### ISSUE THREAD

**Issue by SnowyNoS** [NostraliaWoW/mangoszero#150]
Summary - Two bugs experienced after running SM Library and then Armory. In Library only one person could loot the scarlet key. After they did the lockbox disappeared, then reappeared a few seconds later but was unable to used by anyone, with the error it was currently being used
Secondly after completing armory Herod dropped his raging berzerker helm, however the loot option was not given to myself. The rest of the group all rolled/passed on it, but i was not even shown the loot. The option to roll was not displayed, nor was the info showing who rolled/passed and what loot was even dropped. I thought that no loot dropped until I asked and they linked it. 

Location - SM, library and then armory
Steps to Reproduce - Unsure if it was a one off or always happening. Nothing special, just finished dungeons then tried to loot.
Reported By - Paprika

Post,
http://nostralia.org/forums/viewtopic.php?f=24&t=148

**Comment by natrist** [comment]
The chest issue is now resolved as of #129 and commit #7bea85a
