### ISSUE TITLE
Click to Move not working

### ISSUE THREAD

**Issue by SnowyNoS** [NostraliaWoW/mangoszero#152]
It will follow the click for about 4-5 seconds about on average for me the my character will stop. AL most every time.

Post,
http://nostralia.org/forums/viewtopic.php?f=28&t=151&p=329#p329

**Comment by sundayz** [comment]
Couldn't reproduce. Needs more info, probably just a client thing.

**Comment by SnowyNoS** [comment]
@sundayz Both me and Gut have tried to use Click to move function and it works for about 70% of the way to the place you have clicked and then it will just stop.
