### ISSUE TITLE
Scarlet Monastery Cathedral

### ISSUE THREAD

**Issue by SnowyNoS** [NostraliaWoW/mangoszero#153]
Name - Scarlet Monastery Cathedral,

Summary - The final fight is completely unscripted. Mainly the High Inquisitor, she doesn't automatically walk out and attack everyone you can heal up before pulling her. When she is low she doesn't bubble and res Mograine before healing herself while everyone is slept, restarting the fight with both of them. she doesn't res him at all and she just dies like a pussy.

Location - N/A

Steps to Reproduce - Just do the fight normally.

Screen Shots/Video - N/A

Reported By - Ethug

Extra Information - N/A

Post,
http://nostralia.org/forums/viewtopic.php?f=24&t=153

**Comment by sundayz** [comment]
Fixed in 6ea6f2e.
