### ISSUE TITLE
NPCs Casting Backstab in Front

### ISSUE THREAD

**Issue by SnowyNoS** [NostraliaWoW/mangoszero#154]
Name - NPC - Syndicate Highwayman 
Summary - NPCs are spamming backstab with no global cooldown
Location - Arathi Highlands - Northfold Manor
Steps to Reproduce - 
Screen Shots/Video - 
Reported By - Hifidelity
Extra Information -

**Comment by sundayz** [comment]
Fixed in [database 320be38](https://github.com/NostraliaWoW/database/commit/320be38b82b9742260feac2807382d30b1290d77).

**Comment by sundayz** [comment]
Actually an issue where backstab can be used when the target is facing you. This NPC is _supposed_ to spam the ability if they are behind you.
