### ISSUE TITLE
Anger Management talent makes it so you dont lose rage in combat

### ISSUE THREAD

**Issue by Nostralia** [NostraliaWoW/mangoszero#155]
As the title says, after the latest fixes, when in combat, no rage is lost (only after that talent is chosen)

**Comment by natrist** [comment]
How do I reproduce this bug?

**Comment by sundayz** [comment]
Introduced in 6b9456f (unconfirmed).

Revert that commit if no fix is found before 12pm AEST on Thursday.

**Comment by Nostralia** [comment]
You reproduce it by going into combat, and by noticing you aren't losing any rage. 

We did this by having 1 person tank, and the warrior get into combat and then take a few steps back (so he wasn't getting hit which would generate rage and he wouldnt hit so he wouldnt generate reage)

**Comment by sundayz** [comment]
Is this currently a bug on the live realm?

**Comment by Nostralia** [comment]
Yes, although its not gamebreaking we believe

**Comment by natrist** [comment]
I'm thinking maybe the Anger Management aura actually sets the regeneration rate of rage to 15 (1.5/sec.)
