### ISSUE TITLE
Lower Rune of mazthoril doesn't teleport

### ISSUE THREAD

**Issue by Gutr0t** [NostraliaWoW/mangoszero#157]
Summary - The Rune of Mazthoril in 52,55 in Winterspring / Mazthoril does not teleport the player from the lower rune in the cave to the upper rune on top of the mountain and vice versa.

Steps to Reproduce - Enter Mazthoril Cave and step onto the The Rune of Mazthoril, there is currently no effect.

Video - 
[How it works at the moment](https://vimeo.com/85082064) 
[How it should be working](https://youtu.be/FflTmV9qPd8?t=206)

Extra Information - gobject: [Rune of Mazthoril LT [176164]](http://db.vanillagaming.org/?object=176164) should teleport to [Rune of Mazthoril UT [176165]](http://db.vanillagaming.org/?object=176165)

Spell IDs used: 
Port to Haleh [17159](http://db.vanillagaming.org/?spell=17159)  
Port to Mazthoril [17160](http://db.vanillagaming.org/?spell=17160)

**Comment by sundayz** [comment]
Thanks for the well formatted report.

**Comment by Gutr0t** [comment]
Thanks, i'll try keep this the standard for myself
