### ISSUE TITLE
Goblin Land Mine

### ISSUE THREAD

**Issue by SnowyNoS** [NostraliaWoW/mangoszero#161]
Name - Goblin Land Mine.

Summary - Straight up doesn't explode, just sits there and the mob attacks it until dead.

Location - N/A

Steps to Reproduce - Place land mine on the ground and agro a mob.

Screen Shots/Video - N/A

Reported By - Ethug

Extra Information - https://www.reddit.com/r/Nostralia/ Subscribe plx

Post,
http://nostralia.org/forums/viewtopic.php?f=23&t=158

**Comment by sundayz** [comment]
Fixed in 661a6d8, but the land mine will explode even when friendly creatures step on it due to missing Eluna method for checking unit hostile reaction. @natrist Close since original issue was resolved?

**Comment by sundayz** [comment]
Closed because the original issue is resolved.
