### ISSUE TITLE
Channeling Spells and Resists

### ISSUE THREAD

**Issue by SnowyNoS** [NostraliaWoW/mangoszero#167]
Name - Drain Life, Drain Mana, Drain Soul
Summary - Sometimes (not always) if a drain spell is cast on the target and resisted, the drain animation will still continue, leaving you to channel for spell duration without the damage\effect.
Location - on Cast
Steps to Reproduce - Cast drain spell that is resisted
Screen Shots/Video - N\A
Reported By - Robtheshadow
Extra Information - Basically if it resists, the cast animation shouldn't go ahead.

post,
http://nostralia.org/forums/viewtopic.php?f=29&t=168

**Comment by sundayz** [comment]
Related to #83.
