### ISSUE TITLE
Channeling Spells and DoTs

### ISSUE THREAD

**Issue by SnowyNoS** [NostraliaWoW/mangoszero#168]
Name - Drain Life, Drain Mana, Drain Soul
Summary - DoT damage on caster causing spell pushback 
Location - Casted
Steps to Reproduce - Cast Drain life with a DoT applied to you (e.g poison, rend, etc)
Screen Shots/Video - (Visual evidence of said bug)
Reported By - Robtheshadow
Extra Information - DoT damage should not affect spell pushback.

Post,
http://nostralia.org/forums/viewtopic.php?f=29&t=167

**Comment by natrist** [comment]
Just go to the pushback handler function and figure out a way to differentiate damage over time from instant damage spells.

**Comment by sundayz** [comment]
Please check this issue.

Tried casting Life Drain. Neither Rend nor Corruption caused pushback while channeling on my realm.
