### ISSUE TITLE
Rogue's Endurance talent doesn't change cooldown correctly

### ISSUE THREAD

**Issue by nymacro** [NostraliaWoW/mangoszero#170]
![wowscrnshot_020417_103042](https://cloud.githubusercontent.com/assets/13063751/22614160/9d81841e-eaca-11e6-9353-acdb443fe196.png)

The talent *Endurance* in the Combat tree should reduce the cooldown by 1.5 minutes (45 seconds per point spent) at max.

After using sprint, checking the cooldown will show 4 minutes remaining, with the cooldown being 3.5 mins.

**Comment by pjfry651** [comment]
I think this is the UI rounding the cooldown. I did a quick test and the cooldown with the talent is 3.5 minutes. Please reopen if there is an issue or if you have any info to the contrary.

**Comment by nymacro** [comment]
That looks to be the case. Doing manual timing seems to put it at 3.5 mins. The WoW UI seems to display cooldown vs. cooldown remaining in a differently.

False positive 😄
