### ISSUE TITLE
Echeyakee

### ISSUE THREAD

**Issue by SnowyNoS** [NostraliaWoW/mangoszero#173]
Name - Echeyakee
Summary - Echeyakee is spawning as a beast.
Location - Barrens NE of cross roads, Quest started in Cross Roads
Steps to Reproduce - I skill that effects only Beasts. Tame Beast / Scare beast / Track Beast. for example
Screnshot - 
http://madaddicts.net/images/wowScreeners/WoWScrnShot3_result.png
Reported By - Gir
Extra Information - Pretty much it.

post,
http://nostralia.org/forums/viewtopic.php?f=22&t=171

**Comment by pjfry651** [comment]
Is he not supposed to be a beast?

**Comment by pjfry651** [comment]
Cannot reproduce issue. He spawns as a beast and I can tame, scare, etc. Please reopen if this continues to be a problem.
