### ISSUE TITLE
The Sacred Flame

### ISSUE THREAD

**Issue by SnowyNoS** [NostraliaWoW/mangoszero#177]
When accepting the quest The Sacred Flame you're supposed to get an Etched Phial, the item does not appear in the inventory of the player. The quest is in Ashenvale and started at Zangen Stonehoof in Mulgore Thunderbluff and finished with him.

Post,
http://nostralia.org/forums/viewtopic.php?f=22&t=179

**Comment by sundayz** [comment]
Not a bug. Quest works as intended. To obtain the Etched Phial, you must kill a [Laughing Sister](http://db.vanillagaming.org/?npc=4054). You may then travel to the Moonwell and fill your phial, turning it into a Filled Etched Phial.

From the quest text:

_"To collect the water, you will first need to **obtain one of the phials** carried by the **dryads** near the **Raynewood Retreat** in the heart of Ashenvale Forest. There is a moonwell near the western bank of the Falfarren River, south of the main road, where you can fill the phial."_
