### ISSUE TITLE
Elixir of pain

### ISSUE THREAD

**Issue by SnowyNoS** [NostraliaWoW/mangoszero#178]
The Quest "Elixir of pain " dosen't work.

The Mountain Lions you need to kill in able to recieve the blood don't drop. Killed atleast 30 without 1 single drop

Best Regards.

Ingame name: Stonker

Post,
http://nostralia.org/forums/viewtopic.php?f=22&t=176

**Comment by pjfry651** [comment]
Quite a few people have completed this quest successfully. I have looked up the drop rate, and while it is relatively low, it is still completable.
