### ISSUE TITLE
The Algaz Gauntlet

### ISSUE THREAD

**Issue by SnowyNoS** [NostraliaWoW/mangoszero#183]
Name - The Algaz Gauntlet
Summary - Not offered by quest giver
Location - Loch Modan
Steps to Reproduce - N/A
Screen Shots/Video - N/A
Reported By - Shandy
Extra Information - Mountaineer Rockgar does not offer this quest

post,
http://nostralia.org/forums/viewtopic.php?f=22&t=189

**Comment by SnowyNoS** [comment]
Additional Information:
http://www.wowhead.com/quest=455/the-algaz-gauntlet
According to above link, quest was added in v1.11.1.10958, requires level 19, and is a level 21 quest.

Also, according to: http://db.vanillagaming.org/?quest=455
The quest before it is "Report to Mountaineer Rockgar" (http://db.vanillagaming.org/?quest=468), also requiring level 19, and is a level 21 quest.

**Comment by pjfry651** [comment]
I was able to accept this quest on both dev and live realms as a Level 19.

The prerequisite quest must be completed first "Report to Mountaineer Rockgar" from Mountaineer Kadrell in Thelsamar.
