### ISSUE TITLE
Sunken Temple - Shade of Eranikus

### ISSUE THREAD

**Issue by SnowyNoS** [NostraliaWoW/mangoszero#188]
We have a bug with Shade of Eranikus event. The boss needs to spawn after you have killed Morphaz and Hazzaz, they only spawn once all dragonkin die and this works. But once Morphaz and Hazzaz are dead Shade of Eranikus did not spawn. We have tested this tonight with a group of players and it didn't work.

This needs to be looked at ASAP as most ppl will start doing this every soon. This boss plays a big roll as it gives them a quest and BiS loot for some classes.

http://www.almarsguides.com/wow/instances/sunkentemple.cfm

**Comment by sundayz** [comment]
Fixed in 47f9fd9.
