### ISSUE TITLE
Clearcasting not gained by blizzard

### ISSUE THREAD

**Issue by SnowyNoS** [NostraliaWoW/mangoszero#191]
Name - Clearcasting not gained by blizzard
Summary - Mages cannot gain clearcasting by blizzard, huge and unacceptable bug for mages  :cry: 
Location - ALL
Steps to Reproduce - cast blizzard on mobs
Screen Shots/Video - NA
Reported By - Reinaj
Extra Information - This bug was also in Aussie, I was expecting it fixed here...

Post,
http://nostralia.org/forums/viewtopic.php?f=29&t=196

**Comment by sundayz** [comment]
Possible bug with all auras granted by implicit target spells.

**Comment by natrist** [comment]
@pjfry651 Is this still an issue?

**Comment by pjfry651** [comment]
Hey I think the issue will close itself when the branch is merged back into master. The commit I made fixes it.
