### ISSUE TITLE
Cuergo's Gold

### ISSUE THREAD

**Issue by SnowyNoS** [NostraliaWoW/mangoszero#193]
Name - Cuergo's Gold
Summary - You activate this inconspicuous object and it summons 4 pirates and a chest, all 4 pirates drop keys to open the chest, but the chest despawns before you have the time to kill the pirates.
This quest initially comes from Cuergo's Treasure map, which is created from picking up the lower, middle & upper map fragments dropped from pirates in Lost Rigger Cove of Tanaris
Location - 56,92 in Tanaris
Steps to Reproduce - Collect the map fragments, create the treasure map, run down to the location & click on the object
Screen Shots/Video - n/a
Reported By - Toast
Extra Information - Chest just needs to not despawns

Post,
http://nostralia.org/forums/viewtopic.php?f=22&t=197

**Comment by sundayz** [comment]
Can be backported from cmangos Eluna

**Comment by sundayz** [comment]
I'm unsure about this. I've waited quite a while and the chest didn't despawn. How long do you need to kill those pirates?
