### ISSUE TITLE
Sunken Temple - Gate at Avatar of Hakkar

### ISSUE THREAD

**Issue by SnowyNoS** [NostraliaWoW/mangoszero#196]
After killing Avatar of Hakkar the gates don't open so the players are stock in the Avatar of Hakkar room. 

NPC-8443
Object numbers for the doors are below.
[DOOR1] Gobject 149432
[DOOR2] Gobject 149433

This needs to be looked at before next patch as more and more players are at this lvl range. 

Tested by Gutrot and Snowy

**Comment by sundayz** [comment]
Fixed in f8cfdcc.
