### ISSUE TITLE
The Pickpocket spell shares picked up money with the party

### ISSUE THREAD

**Issue by natrist** [NostraliaWoW/mangoszero#2]
The Rogue spell [Pickpocket](http://classic.openwow.com/spell=5967) currently shares gold with the caster's entire group. The expected behavior is for the gold to be given only to the pickpocket.

**Comment by Gutr0t** [comment]
The Rogue spell Pickpocket is still sharing pick pocketed gold within a group, the rogue casting pick pocket should claim all the gold claimed by pickpocket spell. :)

**Comment by natrist** [comment]
This has been fixed and is the result of the live region realm not being up to date. Thank Zed for that one.
https://www.youtube.com/watch?v=y7Yp2L6c2KM
