### ISSUE TITLE
Blasted Land 4 Quest Give-ins not registering quest complete

### ISSUE THREAD

**Issue by Nostralia** [NostraliaWoW/mangoszero#202]
The 4 quests do not register as completed even when all items have been collected (So I figured I'd put them all as one issue) 

http://db.vanillagaming.org/?quest=2583
http://db.vanillagaming.org/?quest=2581
http://db.vanillagaming.org/?quest=2585
http://db.vanillagaming.org/?quest=2603

I resolved this issue temporarily by .quest complete #id   So I'm assuming it just doesn't know when its supposed to be complete.

**Comment by sundayz** [comment]
If it is an issue, then it's a more general one to do with the quest handler, not these four quests in particular.

In the future, try using /reloadui or moving the items around your bags or into your bank and back.
