### ISSUE TITLE
 Deep Wounds

### ISSUE THREAD

**Issue by SnowyNoS** [NostraliaWoW/mangoszero#206]
Dear GMs,

I have noticed that Deep Wounds does not proc off spells. The debuff is correctly applied to white damage from melee weapons, but fails to apply from Heroic Strike, Overpower, Execute etc. I haven't been able to confirm if Deep Wounds is applied with aoe spells (Thunderclap or Cleave) crits yet.

I have troubleshooted with Gutrot and he is able to confirm this still remains an issue. Resetting my talent points appeared to correct Deep Wounds not applying on white damage, this is thankfully fixed.

With thanks,
Maszakarn
(Mas lvl24 Warrior)

**Comment by mfranca0009** [comment]
Was this issue resolved by the talent reset that was done recently?
