### ISSUE TITLE
Rogue trainer not working

### ISSUE THREAD

**Issue by SnowyNoS** [NostraliaWoW/mangoszero#208]
/Rogue trainers are not working right now, when you try and learn the skill the NPC takes your gold but you don't learn the skill. All rogue trainers are affected. 

Gutrot and I have tested it and the report is true, we have removed the NPC and spawned it back to see if that will fix the problem but it did not. We will test other class NPCs to see if this also effects them to.

Reported by Thetabop
12g will be given back to the player by Snowy on 9/2/17 at 8.42pm
Skill sap was given to the player by Gutrot rank3

**Comment by SnowyNoS** [comment]
Paladin trainers work fine

**Comment by Nolin7777** [comment]
Were you in stealth while you try to learn the skills?

**Comment by Nolin7777** [comment]
work perfectly
