### ISSUE TITLE
 Password character limit WoW

### ISSUE THREAD

**Issue by SnowyNoS** [NostraliaWoW/mangoszero#210]
I registered a login without any issues, set the realmlist correctly and would continuously get "The details you have entered are incorrect..." error, then when I tried to login again I would be banned for using incorrect details twice in a row.

Gutrot did a fantastic job helping me over discord thinking my IP was blacklisted(due to DDOS, etc), but I was only faced with the same issues until I realised the password input within WoW has a maximum character limit and wouldn't accept my entire password(as per I registered).

I then shortened my password and logged in without any issues, so I would suggest that the website registration has a password character limit that matches WoWs so no one else has the same issue.

Post,
http://nostralia.org/forums/viewtopic.php?f=28&t=214

**Comment by sundayz** [comment]
Website issue, not core.

Password field on the website must be given a fixed length, and CMS must check if the password received is <= 16 characters (needs confirm) before adding it to the database.

**Comment by natrist** [comment]
This should probably be assigned to the web dev guy; Can we get him on the GitHub team?

**Comment by SnowyNoS** [comment]
We have a web dev guy?

**Comment by Nostralia** [comment]
Franzz has been notified
