### ISSUE TITLE
Hunters unable to tame Broken Tooth (rare spawn)

### ISSUE THREAD

**Issue by SnowyNoS** [NostraliaWoW/mangoszero#213]
I was attempting to tame Broken tooth, however I recieved an 'invalid target' notification when i cast "tame Beast". I had previously stabled my pet and am a higher level than broken tooth.

post,
http://nostralia.org/forums/viewtopic.php?f=29&t=209&p=467#p467

**Comment by pjfry651** [comment]
Solved by clearing WDB cache files and relaunching game client. Unsure if we can do anything to fix.
