### ISSUE TITLE
Magister Kalendris - Boss on a 25second re spawn timer

### ISSUE THREAD

**Issue by SnowyNoS** [NostraliaWoW/mangoszero#214]
NPC in question http://db.vanillagaming.org/?npc=11487

This boss is on a 25second re spawn timer this needs to be fixed asap please.

I did try and use .npc set spawntime  but this did not work.

**Comment by sundayz** [comment]
Fixed in https://github.com/NostraliaWoW/database/commit/c32d2793e1b7542e6ea3268834bca922fbf9024c.
