### ISSUE TITLE
 Pirate Hats Ahoy!

### ISSUE THREAD

**Issue by SnowyNoS** [NostraliaWoW/mangoszero#217]
Name - Pirate Hats Ahoy!

Summary - Southsea Pirate Hat seems to have a 1%-5% drop rate, and it should be more like 25%. Many other players have confirmed this, I killed about 25 pirates and didn't get a single hat.

Location - Tanaris, Lost Rigger Cove.

Steps to Reproduce - Accept the quest and go kill some pirates.

Screen Shots/Video - N/A

Reported By - Ethug.

Extra Information - <3

Post,
http://nostralia.org/forums/viewtopic.php?f=22&t=218

**Comment by pjfry651** [comment]
The current drop rate is higher than 5%.

I can only see BC comments here: http://db.vanillagaming.org/?quest=8365#wh-comments so I'm not sure how accurate they are for vanilla levels. We need more sources but a small bump in drop rate looks like it might be acceptable.
