### ISSUE TITLE
Reloading UI causes hunter pet bug

### ISSUE THREAD

**Issue by SnowyNoS** [NostraliaWoW/mangoszero#219]
Name - Pet = Twilight Runner (cat is located in Stonetalon Mountains at Stonetalon Peak)
Summary - I recently tamed a new pet, so this is my 2nd pet, i decided to reload my UI, /reload, and i noticed that my pet acts as it is dismissed, the pet's frame is still there but his happy meter disappears and when i tell him to attack something, he will not. I click the call pet skill and it says i already have my pet out. i dismiss my pet and recall him out and everything is back to normal. 
Suppost To Do- I believe that reloading the UI shouldn't effect a hunter's pet like this
Location -I was at Stonetalon Peak
Steps to Reproduce - Reloaded UI while having a pet called out by your side
Screen Shots/Video - Do not have
Reported By - KoKo
Extra Information - Reloading UI makes pet bug out

Post,
http://nostralia.org/forums/viewtopic.php?f=29&t=225

**Comment by sundayz** [comment]
Fixed in 6ff2380.
