### ISSUE TITLE
Nightlash (ID: 1983) casts Spirit Steal (SpellID: 3477) on players.

### ISSUE THREAD

**Issue by SnowyNoS** [NostraliaWoW/mangoszero#22]
Nightlash (ID: 1983) casts Spirit Steal (SpellID: 3477) on players. Should only be cast on gnolls (Sacrifice) nearby to regain health. Discussion on github regarding this; https://github.com/classicdb/database/issues/846

**Comment by pjfry651** [comment]
cmangos fixed this by causing TARGET_RANDOM_UNIT_CHAIN_IN_AREA to act exactly the same as TARGET_RANDOM_FRIEND_CHAIN_IN_AREA.

I'd like to see what else uses TARGET_RANDOM_UNIT_CHAIN_IN_AREA before we use their fix, in case it breaks something else.
