### ISSUE TITLE
Bride of the Embalmer

### ISSUE THREAD

**Issue by SnowyNoS** [NostraliaWoW/mangoszero#227]
Name - Bride of the Embalmer
Summary - Unable to click grave, as such unable to summon enemy to complete quest
Location - Duskwood, raven hill cemetery, behind Abercrombie's shack.
Steps to Reproduce - Be on the quest Bride of the Embalmer
Reported By - Primin

Post,
http://nostralia.org/forums/viewtopic.php?f=22&t=231

**Comment by sundayz** [comment]
@natrist Fixed?

**Comment by natrist** [comment]
Fixed as of [3f09b](https://github.com/NostraliaWoW/mangoszero/commit/3f09b981a50d96b50786b45a7f45f95d3a477f2a)
