### ISSUE TITLE
PvP Consumables

### ISSUE THREAD

**Issue by Gutr0t** [NostraliaWoW/mangoszero#23]
The pvp consumables sold by the pvp vendors are usable anywhere as opposed to ONLY being usable in the battlegrounds they are designated for.

**Comment by natrist** [comment]
What steps would one need to take in order to reproduce the bug?

**Comment by Gutr0t** [comment]
An example would be buying [Combat Healing Potion](http://db.vanillagaming.org/?item=18839) from the Vendors Brave Stonehide or Master Sergeant Biggins. It should only be consumable inside a battleground instance.

**Comment by Gutr0t** [comment]
This bug seems specific to these items:
http://db.vanillagaming.org/?item=17348/
http://db.vanillagaming.org/?item=17351/
http://db.vanillagaming.org/?item=19066/
http://db.vanillagaming.org/?item=20062
http://db.vanillagaming.org/?item=17351/
http://db.vanillagaming.org/?item=17348/
http://db.vanillagaming.org/?item=19060
http://db.vanillagaming.org/?item=19062
http://db.vanillagaming.org/?item=19061
http://db.vanillagaming.org/?item=19067
http://db.vanillagaming.org/?item=19066
http://db.vanillagaming.org/?item=19068

With a bit of testing the bandages and potions seem to be working okay, but PvP rations either work outside the battleground, or it's consumed with no effect instead of the message "must be used in a battleground".

**Comment by Nolin7777** [comment]
[commit-link](https://github.com/NostraliaWoW/mangoszero/commit/76c935872b7765b20943bd4f7c81ca952ea61710)

**Comment by sundayz** [comment]
@Nolin7777 Should this be closed?
