### ISSUE TITLE
Bosss - Eldreth Seether

### ISSUE THREAD

**Issue by SnowyNoS** [NostraliaWoW/mangoszero#231]
This boss is also on a 25second respawn timer.

http://db.vanillagaming.org/?npc=11469

**Comment by SnowyNoS** [comment]
also 
Tendris Warpwood
http://db.vanillagaming.org/?npc=11489

**Comment by sundayz** [comment]
Please confirm that these haven't been spawned by a GM and are in fact default ClassicDB spawns.

**Comment by pjfry651** [comment]
Eldreth Seether does not seem to be a boss.

I could not reproduce a 25 second respawn timer on Tendris. As sundays mentioned, it sounds like a default respawn time for a GM spawned mob.

Please confirm this issue is still valid and reopen if required.
