### ISSUE TITLE
BRD Phalanx reset script

### ISSUE THREAD

**Issue by pjfry651** [NostraliaWoW/mangoszero#239]
When the Phalanx in BRD evades/resets after moving, he is supposed to return to the door. The current reset script can cause an error. in npc_phalanxAI line 647 -> escort_ai line 529. Possible null waypoint?

**Comment by sundayz** [comment]
I'm tidying up the Grim Guzzler scripts.

**Comment by sundayz** [comment]
Fixed in 028cd43, but I'm not happy with this. Perhaps someone else should take a look at the actual reason behind the crash, rather than hack fixing it. I couldn't debug it, I think it's to do with threading.

**Comment by natrist** [comment]
@sundayz Is this still an ongoing issue?

**Comment by sundayz** [comment]
@Natrist Crash is resolved, NPC behaviour is not blizzlike. He teleports to his correct position rather than running to it using waypoints, as they caused the crash.

**Comment by natrist** [comment]
@sundayz @pjfry651 Closed as the original issue is resolved. Might re-open eventually to implement the proper evade behavior.
