### ISSUE TITLE
Verog The Dervish (ID: 3395) (for QuestID: 851)

### ISSUE THREAD

**Issue by SnowyNoS** [NostraliaWoW/mangoszero#24]
Verog The Dervish (ID: 3395) (for QuestID: 851) takes too many Kolkar kills or doesn't spawn. Should take roughly 4 - 6 Kolkar kills within the perimeter of the tent to summon.

**Comment by pjfry651** [comment]
http://db.vanillagaming.org/?quest=851#wh-comments

Comments here state it took quite a few kills to spawn him sometimes, which lines up with the spawn chance that is currently set.

Will close for now, please reopen if you'd like to provide a case for increasing.

**Comment by pjfry651** [comment]
Reopening, chance for this spawn should be increased.
