### ISSUE TITLE
henchman valik

### ISSUE THREAD

**Issue by SnowyNoS** [NostraliaWoW/mangoszero#245]
Name - Henchman Valik -quest name - Valik
Summary - Henchman Valik doesn't give out the quest he is supposed to, instead remaining permanently hostile
Location - alterac mountains 55.8, 68
Steps to Reproduce - Try to pick up the quest, get face punched in
Reported By - Primin
Extra Information - He is supposed to give you a quest, then turn hostile when you complete the quest, on retail there was a bug where if he wasn't killed he would remain hostile for the next person until he was killed and respawned, Ive tried doing this but he respawns hostile never giving out the quest.

post,
http://nostralia.org/forums/viewtopic.php?f=22&t=275&p=577#p577

**Comment by sundayz** [comment]
Fixed in 9a014e0.
