### ISSUE TITLE
Armour/Damage Calculation and Formulas are (Seemingly) Incorrect

### ISSUE THREAD

**Issue by sundayz** [NostraliaWoW/mangoszero#250]
The alarming amount of reports regarding boss damage suggest that there is something amiss with the way in which damage done to players is calculated, either in the defense/armour formula, or in the damage formula.

Please investigate these claims and leave any information you may have in this issue thread.

See reports:
#36, #37, #38, #39, #41,
#42, #44, #47, #48, #49. 
#221, #222, #234, #249.

**Comment by pjfry651** [comment]
I don't think there is an issue with calculation of these boss issues - they just have ridiculous values in the database. Rend Blackhand has a MinMeleeDmg of 1138, and a MaxMeleeDmg of 1180, but his DamageMultiplier is set to 6.5

This means before any calculations are even done for defense, armour, etc. etc. he's got about a 7k hit lined up.

**Comment by Nolin7777** [comment]
> I don't think there is an issue with calculation of these boss issues - they just have ridiculous values in the database. Rend Blackhand has a MinMeleeDmg of 1138, and a MaxMeleeDmg of 1180, but his DamageMultiplier is set to 6.5
> 
> This means before any calculations are even done for defense, armour, etc. etc. he's got about a 7k hit lined up.

You are right @pjfry651

**Comment by Nolin7777** [comment]
I will create an UPDATE SQL for the affected Dungeon NPCs

**Comment by pjfry651** [comment]
All associated issues are closed.
