### ISSUE TITLE
Engineering: Target Dummy

### ISSUE THREAD

**Issue by SnowyNoS** [NostraliaWoW/mangoszero#284]
Name - Target Dummy (engineering)
Summary - Target Dummy is not despawning / dying after 15 seconds. It will stay around, follow, and damage enemies until the player has logged off and on or until the player/target dummy dies. It is not lootable upon its death.

The target dummy is only suppose to last for 15 seconds or until it's death. While spawned it is suppose to mass taunt everything within a certain range (I do not have the info on this) every couple of seconds. Presumably from the moment you spawn it recurring every 3 seconds for a total of 15 seconds. After the target dummy has died, be it from combat or running out of time it is intended to be lootable. It's loot table should include a few of the items used to make it and a fused wiring with a 10-15% drop chance. Multiple sources, that are easy to find indicate this.

Location - Everywhere
Steps to Reproduce - Create and use target dummy. Proceed to move around for as long as you like.
Screen Shots/Video - N/A
Reported By - Kazrid
Extra Information - N/A

post,
https://nostralia.org/forums/viewtopic.php?f=23&t=317

**Comment by sundayz** [comment]
**Spell:** http://db.vanillagaming.org/?spell=4044
@SnowyNoS Does the Masterwork Target Dummy and Advanced Target Dummy exhibit correct behaviour, or are they missing scripts too?

**Comment by sundayz** [comment]
Fixed in 7a4af31, but creatures refuse to behave nicely around dummies, no matter what faction/flag/bytes they are given. Creatures will constantly attack, then stop attacking when they are forced to via the first taunt, and then seemingly ignore threat that comes from the periodic taunts.

**Comment by sundayz** [comment]
@natrist Close since original issue was resolved? Guardian pet AI seems broken.

**Comment by natrist** [comment]
@sundayz If the original issue is resolved, then go ahead and close it. We will open a new one if a different bug is found.

**Comment by SnowyNoS** [comment]
Afternoon,

As we have closed this aka we fixed it "did nothing as the Guardian pet AI seems broken" Do I A, tell the person no we can't fix it or B, we are going to try and work this out again?

**Posted on the forum from the player** 
Update: After patch notes I tested Advanced Target Dummy and it still appears to be bugged.

Screenshot - http://prntscr.com/ehzama

As you can see, my target dummy is off cool down (2 minutes) and the one I used earlier is still up and still has everything wrong with it that I pointed out in my report
