### ISSUE TITLE
Ramstien the Gorger

### ISSUE THREAD

**Issue by SnowyNoS** [NostraliaWoW/mangoszero#285]
Summary - 
After wiping on the boss in Stratholm Undead side Ramstien the Gorger - upon re-entering the instance the boss had despawned and the doors to both the front of the ziggurat and to baron's room were closed.
Location - Courtyard before Baron Rivendare
Steps to Reproduce - Called a GM to open the doors and respawn the boss

Reported By - Recon

post,
https://nostralia.org/forums/viewtopic.php?f=24&t=307

**Comment by Nolin7777** [comment]
The door reopens if **everybody** is setting the spirit free.
