### ISSUE TITLE
Blacksmithing: Choose Your Fate Bug

### ISSUE THREAD

**Issue by mfranca0009** [NostraliaWoW/mangoszero#299]
Will not let you choose being a armorsmith or weaponsmith, if you click on either of the options it does nothing. 

NPC: Myolor Sunderfury

Location: Ironforge

Reproduce: Believe you should have 150 skill for blacksmithing or more then speak to Myolor Sunderfury to choose being a armorsmith or weaponsmith.

**Comment by SnowyNoS** [comment]
Please close this as its working as intended.
