### ISSUE TITLE
Items Lost on Quest Reward When Multiple Items Involved

### ISSUE THREAD

**Issue by sundayz** [NostraliaWoW/mangoszero#3]
**Info: ** low bag space on q turn in - Refer to http://nostralia.org/forums/viewtopic.php?f=22&t=39

**Comment by sundayz** [comment]
Players always need X + 1 bag slots free, e.g. 3 bag slots when 2 free should be enough.

**Comment by sundayz** [comment]
Fixed in 31fa48c.

**Comment by Nostralia** [comment]
When attempting to complete a quest that rewards 4 rewards with only 2 slots available, the player is told he does not have enough space (which is the initial fix that was implemented, so thats good), but the player then proceeds to free up 2 slots, and then completes the quest, and still only receives 2 rewards even with 4 slots available.

**Comment by pjfry651** [comment]
More info while I remember:

Quest is Captain Sander's Hidden Treasure (Part 4) (ID: 140)
Items rewarded were: Silver Bar (2842) and Captain Sander's Shirt (3342)
Items missed were: Captain Sander's Sash (3344) and Captain Sander's Booty Bag (3343)

**Comment by sundayz** [comment]
The check happens too soon, which is why the 'Quest Complete' sound plays.

**Comment by sundayz** [comment]
Assigned @natrist because he provided initial fix.

**Comment by natrist** [comment]
@Nostralia I can't reproduce the issue on my end. Can you guys provide some more quest examples?
@pjfry651 Captain Sander's Hidden Treasure (140) does NOT display the mentioned behavior.
