### ISSUE TITLE
Rin'ji is Trapped!

### ISSUE THREAD

**Issue by SnowyNoS** [NostraliaWoW/mangoszero#302]
The npc http://db.vanillagaming.org/?npc=7780 runs at sprint speed, ppl can't keep up with it.

**Comment by sundayz** [comment]
He definitely walks. He will start running once he sees the path. You only have to keep up with him for about 10 seconds, at which point you receive credit for the quest and he leaves. You don't have to follow him after you get the quest completion credit.

**Comment by SnowyNoS** [comment]
Cool I will let the player know
