### ISSUE TITLE
Honor from HKs not being rolled over every week

### ISSUE THREAD

**Issue by Nostralia** [NostraliaWoW/mangoszero#311]
Here is an extract from mangos.conf:

MaintenanceDay
       The day of the week is performed server maintenance ( currently used for Honor distribution )
       range (0..6): 0 is the first day of the week (normally sunday), 6 is the latest
       Default: 3 (Wednesday in EU)

This Honor distribution happened LAST week, but it did not happen THIS week. While it is a small issue now, its better to get it fixed now than later as more and more people are doing pvp. 

Please contact Zed for more information -

**Comment by sundayz** [comment]
@natrist We should sort out these honour issues. Elysium leaks included a tool that is used to update honour. We should look at the source code to see how they do it.

**Comment by natrist** [comment]
This is likely caused by the world server crashing around the same time the data gets saved.
