### ISSUE TITLE
manual of eviscerate

### ISSUE THREAD

**Issue by SnowyNoS** [NostraliaWoW/mangoszero#323]
Name - Upperblackrock Spire
Summary - Aq20 loot inside instance (manual of eviscerate ix)
Location - Blackrock Spire
Steps to Reproduce - Kill mobs inside
Screen Shots/Video - n/a
Reported By - Madworld
Extra Information - Some people may even be stockpiling this book, some upset people upon said items deletion
(in the same way the players have stock piled silithus loot!)

post,
https://nostralia.org/forums/viewtopic.php?f=24&t=369&p=861#p861

**Comment by mfranca0009** [comment]
Kel has made changes so that this item should be removed from loot table from Blackhand Assassins at server restart.

**Comment by pjfry651** [comment]
See NostraliaWoW/database#e16733295469c626e7c4338a0eb0791e5493cd23

**Comment by mfranca0009** [comment]
This item has been removed from the loot table of Blackhand Assassins which is the only NPC that dropped this. Closing issue.
