### ISSUE TITLE
Shield Bash does not silence spells school

### ISSUE THREAD

**Issue by Gutr0t** [NostraliaWoW/mangoszero#46]
Shield Bash (SpellID: 72 and other ranks) does not silence the interrupted spells' school for 6 seconds as the tooltip mentions.

**Comment by pjfry651** [comment]
Possibly bug with all spell school interrupts, including Earth Shock.

**Comment by sundayz** [comment]
Does it work just on players, or on neither players nor NPCs?

**Comment by sundayz** [comment]
@natrist Halp. See 8285310 for the first part of this fix.

**Comment by natrist** [comment]
@sundayz what seems to be the issue?

**Comment by sundayz** [comment]
Silence effects now add cooldowns to creatures' spells, but spells are still casted. Possibly an issue with ScriptDev, ACID & Eluna. That, or issue with CheckCast in Spell.cpp

**Comment by sundayz** [comment]
Fixed in be13dab.

Player pets can now be silenced and spell school locked, just like players.
NPCs can now be silenced and spell school locked, just like players.

CreatureAI (pets included) now take spell cooldowns into account when deciding whether or not they can cast a spell.
