### ISSUE TITLE
Garr's Antimagic Pulse Doesn't Work

### ISSUE THREAD

**Issue by sundayz** [NostraliaWoW/mangoszero#5]
**Spell:** http://db.vanillagaming.org/?spell=19492

Garr casts the spell as intended, but the effect does not dispel any magic buffs from players.

**Comment by Nolin7777** [comment]
fixed in https://github.com/NostraliaWoW/mangoszero/commit/42d131a0e200b7fae22d755d8e1db811b5bc7a7e
