### ISSUE TITLE
Ghost-o-plasm Round Up - Quest item doesn't summon ghosts

### ISSUE THREAD

**Issue by Nostralia** [NostraliaWoW/mangoszero#75]
Ghost-o-plasm Round Up - Quest ID - 6134 - The quest item doesn't summon ghosts to kill for quest.

**Comment by mfranca0009** [comment]
![no ghosts](https://cloud.githubusercontent.com/assets/26092980/23415787/509de8b2-fdae-11e6-849a-a66c41203a15.png)

**Comment by sundayz** [comment]
Fixed in 661a6d8.
