### ISSUE TITLE
Thistlefur Avenger Enrage

### ISSUE THREAD

**Issue by sundayz** [NostraliaWoW/mangoszero#8]
**Creature Id:** 3925

Supposed to enrage at 30% health (30% chance) or when a nearby friendly is <20% hp.

Currently using ACID, will be rescripted in lua.

**Comment by sundayz** [comment]
Fixed in 405a107.

**Comment by stevenlomas** [comment]
Thistlefur Avengers ignore stealth at the moment.

**Comment by sundayz** [comment]
I don't know what that means?

**Comment by stevenlomas** [comment]
They see stealthed rogues, as if they are not in stealth. The only mob in the game I've found so far to do this (without the seeing eye above their head)
