### ISSUE TITLE
Deadmines NPC Spells

### ISSUE THREAD

**Issue by Gutr0t** [NostraliaWoW/mangoszero#85]
Defias Pirates (ID: 657) not using Bloodsail Companion (Spell ID: 5172)

 Goblin Craftsman (ID: 1731) are using Summon Remote-Controlled Golem (Spell ID: 3605) when they should not.

(Deadmines) Defias Blackguard (ID: 636) not using Cheap Shot (Spell ID: 1833) nor Rupture (Spell ID: 14903)

**Comment by sundayz** [comment]
Goblin Craftsman is supposed to use his summon. The NPC and spell were added in patch 1.11 and I couldn't find anything saying they didn't have them then, only a Wowhead comment confirming they summoned the golems in patch 2.0.3.

Defias Pirates have a 30% chance of summoning the parrot (Bloodsail Companion).
