### ISSUE TITLE
Kodo Roundup

### ISSUE THREAD

**Issue by sundayz** [NostraliaWoW/mangoszero#9]
**Quest Id:** 5561

Missing script.

**Comment by Nostralia** [comment]
Currently, kodo retrieval does give credit unless the kodo is killed (which didnt happen previously, it didnt even give you credit if you .die the kodo). So this needs to be looked into again and tested -

**Comment by sundayz** [comment]
c388ff0 fixes this. (Needs confirm)

**Comment by sundayz** [comment]
Fixed in 172b8167 and tested.

**Comment by Nostralia** [comment]
The kodo is not "tamable" anymore using Kodo Kombobulator. The glyph shows above the kodo when casted, but nothing happens thereafter

**Comment by Nostralia** [comment]
Works after correct lua folder contests set
