### ISSUE TITLE
UBERS Finkle should spawn once beast is skinned

### ISSUE THREAD

**Issue by Nostralia** [NostraliaWoW/mangoszero#96]
Upper Blackrock Spire - Finkle is meant to spawn once the beast is skinned, not once beast is dead.

**Comment by natrist** [comment]
[The Beast](http://classic.openwow.com/npc=10430#abilities) should cast [Finkle is Einhorn](http://classic.openwow.com/spell=16710) upon being skinned by a player.
Files are:

- [instance_blackrock_spire.cpp](https://github.com/mangos/ScriptDev3/blob/50aac6f69bc164e8211b1f3eb6914d3b5ce725aa/scripts/eastern_kingdoms/blackrock_mountain/blackrock_spire/instance_blackrock_spire.cpp)
- [blackrock_spire.h](https://github.com/mangos/ScriptDev3/blob/50aac6f69bc164e8211b1f3eb6914d3b5ce725aa/scripts/eastern_kingdoms/blackrock_mountain/blackrock_spire/blackrock_spire.h)

**Comment by Nostralia** [comment]
The code that makes Finkle spawn when The Beast is skinned works, but you need to remove the part where he spawns when The Beast dies. Currently Finkle spawns when The Beast dies + when The Beast is skinned

**Comment by pjfry651** [comment]
There is a commit for the database repo too that stops this from happening. The spawn on death event was defined in there. https://github.com/NostraliaWoW/database/commit/d7d8019250f8671448c7b07d30bada35d2cb336a

**Comment by natrist** [comment]
As @pjfry651 mentioned, the issue has been confirmed as fixed.
